import {v2 as cloudinary} from 'cloudinary';
import fs from 'fs';

cloudinary.config({ 
        cloud_name: process.env.CLOUDINARY_CLOUD_NAME, 
        api_key: process.env.CLOUDINARY_API_KEY, 
        api_secret: process.env.CLOUDINARY_API_SECRET 
    });

const uploadOnCloudinary = async (localFilePath) =>{
    try {
        if(!localFilePath) return null;

        const response = await cloudinary.uploader.upload(localFilePath,{
            resource_type: "auto"
        })

        fs.unlinkSync(localFilePath);//remove on succession

        //return response
        return {
            url: response.secure_url,
            public_id: response.public_id
        }
    } catch(error){
        fs.unlinkSync(localFilePath); //if upload fails
        return null;
    }
}

const deleteFromCloudinary = async (public_id) => {
    //public_id is a unique identifier that Cloudinary assigns to every file you upload.
    /* 
    you need it to:
        Delete the image from Cloudinary
        Update/replace the image
        Generate different versions of the image (resize, crop, etc.)
    */
    try {

        if (!public_id) return null

        const response = await cloudinary.uploader.destroy(public_id)

        return response

    } catch (error) {
        return null
    }
}

export default deleteFromCloudinary
export default uploadOnCloudinary;


/*
public_id :- A filename, but generated by Cloudinary. For example:
                "public_id": "chat_app/avatars/abc123xyz"

When a user changes their profile picture, you need to:

Delete the old image from Cloudinary → you need the old public_id
Upload the new image → Cloudinary gives you a new public_id
Save the new public_id in your DB

Without saving public_id, you'd upload endlessly and never be able to delete old images — wasting Cloudinary storage.
That's exactly why your code saves both url (to display the image) and public_id (to manage it later).Sonnet 4.6
*/